### ISSUE TITLE
Error with connecting the Bitstamp API

### ISSUE THREAD

**Issue by ReneFroger** [niedbalski/emacs-btc-ticker#3]
Hi There! Thanks for this useful package. It worked fine for many months. 

But suddenly, when I'm sure nothing is changed in my extensive Emacs configuration, I got some errors when starting up Emacs, from btc-ticker. There are propabably issues when connecting with the Bitstamp API: 

`REQUEST [error] Error (error) while connecting to https://www.bitstamp.net/api/ticker/. [4 times]`

Am I the only one here?

**Comment by niedbalski** [comment]
Rene;

I am not having this issue, perhaps is an error with your environment reaching the https://www.bitstamp.net/api/ticker/ URL.

I will close this bug, but if you keep experiencing this, please re-open this.
